### ISSUE TITLE
收不到消息

### ISSUE THREAD

**Issue by Passerby1011** [Tian-que/nonebot-adapter-kaiheila#18]

**Comment by Passerby1011** [comment]
02-14 13:54:34 [SUCCESS] nonebot | Kaiheila 535876439 | [message.private.kmarkdown]: Message cdb2ddf5-7535-425e-af23-5937148eb6c1 from 3716698941 "历史上的今天"
02-14 13:54:34 [DEBUG] nonebot | Checking for matchers in priority 1...
02-14 13:54:34 [DEBUG] nonebot | Checking for matchers in priority 15...
02-14 13:54:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_today_in_history)
02-14 13:54:34 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_today_in_history)
02-14 13:54:34 [DEBUG] nonebot | Running handler Dependent(call=_)
02-14 13:54:34 [DEBUG] nonebot | Handler Dependent(call=_) skipped
02-14 13:54:34 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_today_in_history) running complete
02-14 13:54:34 [DEBUG] nonebot | Stop event propagation
02-14 13:54:34 [DEBUG] nonebot | Checking for matchers completed
这是运行日志

**Comment by ssttkkl** [comment]
这个插件只适配OneBot协议，所以没法执行指令

https://github.com/AquamarineCyan/nonebot-plugin-today-in-history/blob/e447177bd84166b82b24d59322c29f91fa91adf7/nonebot_plugin_today_in_history/__init__.py#L7
