### ISSUE TITLE
只能接受到消息但是好像没有消息内容

### ISSUE THREAD

**Issue by VioL1n** [Tian-que/nonebot-adapter-kaiheila#2]
07-02 12:25:18 [SUCCESS] nonebot | NoneBot is initializing...
07-02 12:25:18 [INFO] nonebot | Current Env: prod
07-02 12:25:18 [SUCCESS] nonebot | Succeeded to import "echo"
07-02 12:25:18 [SUCCESS] nonebot | Running NoneBot...
07-02 12:25:18 [INFO] nonebot | Application startup completed.
07-02 12:25:18 [INFO] nonebot | Kaiheila | Bot 3024181353 connected
07-02 12:25:24 [SUCCESS] nonebot | KAIHEILA 3024181353 | [message.private.kmarkdown]: Message 493eb23f-7f6f-4b32-b997-7847028358c1 from 534286126 ""

bot.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import nonebot
from nonebot.log import logger, default_format
from nonebot.adapters.kaiheila import Adapter as KaiheilaAdapter

nonebot.init()

driver = nonebot.get_driver()
driver.register_adapter(KaiheilaAdapter)

#nonebot.load_from_toml("pyproject.toml")
nonebot.load_builtin_plugins("echo")
#nonebot.load_plugin('hikari_bot')

    

if __name__ == "__main__":
    # logger.warning("Always use `nb run` to start the bot instead of manually running!")
    # nonebot.run(app="__mp_main__:app")
    nonebot.run()

**Comment by VioL1n** [comment]
不知道是不是因为bot读不出我发的消息内容所以不会说话

**Comment by miangou** [comment]
因为官方把接口改了

**Comment by miangou** [comment]
近期，我们会针对消息系统做一次升级，目标是减少消息类型。
我们会将之前类型为1的普通消息，转换为类型为9的 [KMarkdown](https://developer.kaiheila.cn/doc/kmarkdown) 消息， 后续整体系统中文本消息将只有 KMarkdown 类型消息。
希望各位开发者能够做好类型变更的适配，以免系统升级之后导致机器人现有功能不可用。

**Comment by VioL1n** [comment]
哦哦好的谢谢解答
