### ISSUE TITLE
User的nikname字段名称问题

### ISSUE THREAD

**Issue by wangyw15** [Tian-que/nonebot-adapter-kaiheila#20]
[官方文档](https://developer.kookapp.cn/doc/http/user)的`user_view`返回用户昵称的字段是`nickname`，现在的代码里还是`nikname`，貌似拿不到昵称

**Comment by Tian-que** [comment]
#21 已修正，请更新到v0.2.6

**Comment by Tian-que** [comment]
才发现上次只改了tag一直没发版本 = =

**Comment by Tian-que** [comment]
抱歉仰卧起坐了，确认了下是一直没发release，版本有正常推到pypi
