### ISSUE TITLE
希望能补上/api/v3/direct-message/view的api

### ISSUE THREAD

**Issue by canxin121** [Tian-que/nonebot-adapter-kaiheila#22]
因为我需要获取某条 回复的私聊消息 的消息详情，而event获取的extra中body是None值，需要调用/api/v3/direct-message/view才能获取 这个消息回复的消息 的消息msg_id

**Comment by Tian-que** [comment]
明天我看下哈，运气好的话明晚会发个新版

**Comment by Tian-que** [comment]
试试这个 [v0.2.7](https://pypi.org/project/nonebot-adapter-kaiheila/)

**Comment by canxin121** [comment]
嘎嘎好用，可以了
