### ISSUE TITLE
机器人无法正常处理消息

### ISSUE THREAD

**Issue by XM12G** [Tian-que/nonebot-adapter-kaiheila#4]
所有消息为空，如下图
![image](https://user-images.githubusercontent.com/35884945/180643162-9ad06710-fdba-48df-ad0e-ada443fe0d4c.png)
所以为无法正常响应请求

**Comment by XM12G** [comment]
好了，已经解决了，只需要下载整个项目，把最新的项目包放到nonebot的adapters下就行
另外能不能更新下pip包啊，版本很老了

**Comment by Tian-que** [comment]
> 好了，已经解决了，只需要下载整个项目，把最新的项目包放到nonebot的adapters下就行 另外能不能更新下pip包啊，版本很老了

了解，今晚回去推一下

**Comment by ssttkkl** [comment]
其实是我修好以后不知道有没有问题想先测试几天（）
看起来是没太大问题的
