### ISSUE TITLE
退出频道的接口参数似乎有问题

### ISSUE THREAD

**Issue by Cypas** [Tian-que/nonebot-adapter-kaiheila#57]
![image](https://github.com/Tian-que/nonebot-adapter-kaiheila/assets/53274578/6fb8bc0a-cea2-4af8-838b-7f14d7728926)

**Comment by Tian-que** [comment]
这里函数签名限制了必须使用关键字传参
https://github.com/Tian-que/nonebot-adapter-kaiheila/blob/8bdb5b76df0179397ee742db84900a5b69f01e45/nonebot/adapters/kaiheila/api/client.pyi#L193

可以尝试
```python
await bot.guild_leave(guild_id=guild_id)
```

**Comment by Cypas** [comment]
关键字传参后就可用了
