### ISSUE TITLE
如何根据user_id构造User类型

### ISSUE THREAD

**Issue by XM12G** [Tian-que/nonebot-adapter-kaiheila#7]
如何根据user_id构造User类型

另外，t = await bot.call_api("/user/view", user_id = user.id_)，这样子调用用户详情api，会报错：
<ActionFailed code=40000, message=User Id不能为空。, data={}>

**Comment by ssttkkl** [comment]
已解决，参照这个文档：https://github.com/Tian-que/nonebot-adapter-kaiheila/blob/master/MANUAL.md

@Tian-que 是否需要再打一个包

**Comment by Tian-que** [comment]
> 已解决，参照这个文档：https://github.com/Tian-que/nonebot-adapter-kaiheila/blob/master/MANUAL.md
> 
> @Tian-que 是否需要再打一个包

机场过期了pull不了更新，等周末吧，到时候配个发包工作流

**Comment by XM12G** [comment]
OK
